---
Name: raygun
---
### Disable Raygun user tracking to improve performance through caching ###
SilverStripe\Raygun\disableUserTracking: true
SilverStripe\Core\Injector\Injector:
  SilverStripe\Raygun\RaygunHandler:
    constructor:
      RaygunClient: %$Raygun4php\RaygunClient
  Raygun4php\RaygunClient:
    factory: 'SilverStripe\Raygun\RaygunClientFactory'
---
Only:
  envorconstant: 'SS_RAYGUN_APP_KEY'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$SilverStripe\Raygun\RaygunHandler ]]
