---
Name: raygun
---
# Setting to disable Raygun user tracking.
# Avoids setting a cookie and hence improve performance
Raygun4php\RaygunClient:
  disable_user_tracking: true
SilverStripe\Core\Injector\Injector:
  SilverStripe\Raygun\RaygunHandler:
    constructor:
      RaygunClient: %$Raygun4php\RaygunClient
  Raygun4php\RaygunClient:
    factory: 'SilverStripe\Raygun\RaygunClientFactory'
---
Only:
  envorconstant: 'SS_RAYGUN_APP_KEY'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$SilverStripe\Raygun\RaygunHandler ]]
