---
Name: raygun
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Raygun\RaygunHandler:
    properties:
      RaygunClientFactory: 'SilverStripe\Raygun\RaygunClientFactory'
---
Only:
  envorconstant: 'SS_RAYGUN_APP_KEY'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$SilverStripe\Raygun\RaygunHandler ]]
